Repository ProyectoIntegrador2018/BlueMarket, pull requests merged in 2019-03, with the labels that each got.

#67 Added migration for pivot course_user
  app/Http/Controllers/CourseController.php
  database/migrations/2019_02_28_045751_create_courses_table.php
  database/migrations/2019_03_01_014728_course_user.php
Labels: migration

#129 Front-end work for Course details
  resources/views/courses/details.blade.php
Labels: frontend, integrador, wip

#137 Script and instructions to populate DB with mock data
  tests/Mock/instructions.md
  tests/Mock/mock.sql
Labels: integrador, sprint 2
