Repository ProyectoIntegrador2018/BlueMarket, pull requests merged in 2019-04, with the labels that each got.

#142 Auth middleware to users controller
  app/Http/Controllers/UserController.php
Labels: bug

#145 Change category to label in Tag Enum
  database/migrations/2019_04_04_213230_change_enum_name_to_tags.php
Labels: migration

#173 Course creation fixes
  resources/views/courses/create.blade.php
Labels: enhancement, frontend, integrador, sprint 3
